site_name: OpenDNP3 3.0.0
copyright: 'Copyright Automatak LLC 2015-2020'
site_description: 'dnp3 scada opendnp3 library documentation'
repo_url: https://github.com/dnp3/opendnp3
theme:
  name: 'material'  
  palette:
    primary: 'blue'
    accent: 'orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
markdown_extensions:
  - admonition
  - codehilite
nav:
- Introduction: 'index.md'
- Features: 'features/features.md'
- Changes to 3.x release: 'features/3.0.md'
- Build:
  - 'Requirements': 'build/requirements.md'
  - 'Source Tree': 'build/source.md'
  - 'CMake': 'build/cmake.md'
  - 'Linux': 'build/linux.md'
  - 'Windows': 'build/windows.md'
  - 'Java': 'build/java.md'
- API:
  - 'Architecture': 'api/architecture.md'
  - 'Logging': 'api/logging.md'
  - 'Channels': 'api/channels.md'
  - 'TLS Support': 'api/tls.md'
  - 'Link-Layer': 'api/linklayer.md'
  - 'Masters': 'api/masters.md'
  - 'Outstations': 'api/outstations.md'
- Troubleshooting: 'troubleshooting/troubleshooting.md'

