site_name: opendnp3
site_favicon: 'img/favicon.ico'
copyright: 'Copyright Automatak LLC 2015'
site_description: 'dnp3 scada opendnp3 library documentation'
repo_url: https://github.com/automatak/dnp3
theme: cosmo

pages:
- Home: 'index.md'
- DNP3: 'dnp3/dnp3.md'
- Features: 'features/features.md'
- Build:
  - 'Requirements': 'build/requirements.md'
  - 'Libraries': 'build/libraries.md'
  - 'CMake': 'build/cmake.md'  
  - 'Linux': 'build/linux.md'
  - 'Windows': 'build/windows.md'
- API:
  - 'Architecture': 'api/architecture.md'
  - 'Logging': 'api/logging.md'